services:
  mlflow:
    build:
      context: .
      dockerfile: mlflow.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlflow.db:/app/mlflow.db
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:8080
    command: ["mlflow", "server", "--host", "0.0.0.0", "--port", "8080", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "../mlruns"]
    networks:
      - ml_network

  jupyter:
    build:
      context: .
      dockerfile: jupyter.Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
    networks:
      - ml_network

volumes:
  mlruns:
  notebooks:

networks:
  ml_network:
    driver: bridge